file  ::= SPC? expr SPC?

expr  ::= bin | un | term

un    ::= min | plus | star | slsh

min   ::= "-" SPC? expr
plus  ::= "+" SPC? expr
star  ::= "*" SPC? expr
slsh  ::= "/" SPC? expr

bin   ::= div | mul | sub | add
div   ::= term SPC? "/" SPC? expr
mul   ::= term SPC? "*" SPC? expr
sub   ::= term SPC? "-" SPC? expr
add   ::= term SPC? "+" SPC? expr

term  ::= name | lit | group
group ::= "(" SPC? expr SPC? ")"
name  ::= WORD
lit   ::= int
int   ::= [0-9](SPC? [0-9])*

WORD  ::= [a-zA-Z_] [a-zA-Z0-9_]*
SPC   ::= [ ]+
